### ISSUE TITLE
Add links to original repo when it is available to the plugin manifest

### ISSUE THREAD

**Issue by Hecter94** [Hecter94/EndlessSky-PluginArchive#11]
For any plugins who still have an active repository, I would like to include a link to that repository in the manifest file, so people know where to look to check for updates, as the archive isn't always updated, and as a way of attributing the original source of the plugin. 

Suggested format for link:
\[40k Pack](https://github.com/1010todd/Endless-Sky-40K)

**Comment by zuckung** [comment]
Btw this issue and some others are outdated for a while now.
