### ISSUE TITLE
New plugin to add to list

### ISSUE THREAD

**Issue by 43897689431805741092** [Hecter94/EndlessSky-PluginArchive#138]
Category: Ships
https://github.com/43897689431805741092/RW-Ships

**Comment by Hecter94** [comment]
There's a [template](https://github.com/Hecter94/EndlessSky-PluginArchive/issues/new?assignees=Hecter94&labels=New+Submission&projects=&template=plugin-submission.yml&title=New+Plugin+Submission) you can fill out to make sure that all of the information is present and accurate.
