### ISSUE TITLE
Update RW-Ships plugin info

### ISSUE THREAD

**Issue by 43897689431805741092** [Hecter94/EndlessSky-PluginArchive#141]
New future-proofed description is now:
> A small collection of custom ships: primarily drones and multipurpose freighter/utility ships, most of which can carry varying amounts of drones. If the ES Defense Drone Plugin is also installed, non-miner merchants will be loaded with Defense Drones.

The repository link says `N/A` but should say `https://github.com/43897689431805741092/RW-Ships`
I think I failed to provide that link when submitting the plugin; is the "website" field where that was supposed to go?

**Comment by Hecter94** [comment]
> The repository link says `N/A` but should say `https://github.com/43897689431805741092/RW-Ships` I think I failed to provide that link when submitting the plugin; is the "website" field where that was supposed to go?

Yes. Some plugins are hosted elsewhere, not necessarily on GitHub.

**Comment by 43897689431805741092** [comment]
> > The repository link says `N/A` but should say `https://github.com/43897689431805741092/RW-Ships` I think I failed to provide that link when submitting the plugin; is the "website" field where that was supposed to go?
> 
> Yes. Some plugins are hosted elsewhere, not necessarily on GitHub.

Are there any particular other places that people tend to use a lot?

**Comment by Hecter94** [comment]
ModDB comes up occassionally 
https://www.moddb.com/mods?filter=t&&game=45939
