### ISSUE TITLE
Downloading individual plugins

### ISSUE THREAD

**Issue by Hecter94** [Hecter94/EndlessSky-PluginArchive#15]
Github does not support downloading a single folder, you have to download the entire repo. This is annoying for anyone that wants to download just a single plugin and doesn't want the entire 3gb+ repo. 

Terin suggested a third party tool which is able to do this, which I have included in the readme along with a short description of what the limitation is and why the tool is there, but I believe this is a clunky fix.

Should we host every plugin in their own repo? Can we make a file with download links for each plugin? Is there anything in github that can be used to streamline this process?

**Comment by Hecter94** [comment]
Perhaps, it's definitely something to consider. You're right that an individual repo would add a ton of overhead to the project as a whole, and I worry that we'd start to tread into "Stealing and reuploading someone else's work" territory, which we're already straying the line on that. 
If we can't find a better solution though, this might be the route we end up taking.

**Comment by DJF113** [comment]
The other option would be just to continue as we are, and push users toward using the link to the primary source. In which case the manifest would be shown as a comprehensive list, and the archive would only be linked if there is no other source found. That would somewhat help with the issue of downloading them individually, and it might help with the feeling of reuploading other people's work. Just some thoughts, hopefully there's some use to them.

**Comment by Hecter94** [comment]
This is mostly resolved with the addition of:
https://github.com/Hecter94/EndlessSky-PluginArchive/commit/6bf9d3cadfd62c77652aae9c36302aa0070940e9

Individual plugins can now be downloaded from the releases page.
