### ISSUE TITLE
NA != N/A (in plugin listfiles)

### ISSUE THREAD

**Issue by zuckung** [Hecter94/EndlessSky-PluginArchive#173]
The scripts currently only work correct with the listfiles if the phrase 'N/A' , for missing link/description etc, is used. 
It would be more userfriendly if NA or even nothing(empty space) would also be accepted.

Putting that here on the issue list for future fixing. 
If that that, and the the quotation marks bug, is urgent for you, and you don't want to work into the scripts by yourself, i would do that. Else, lets wait for more problems.

**Comment by Hecter94** [comment]
Temporarily fixed with https://github.com/Hecter94/EndlessSky-PluginArchive/commit/72034f4a684642504c0037f46670fdc5e531ea93
No rush for a proper fix.
