### ISSUE TITLE
Inquiry about Plugin Origin

### ISSUE THREAD

**Issue by VaelophisNyx** [Hecter94/EndlessSky-PluginArchive#186]
Hey! original author of the "Titans" plugin here (cleanTechnologist)
May I ask where you got it from? Was pretty sure it had been lost to time at this point ^^;

**Comment by Hecter94** [comment]
For a while, I was accepting plugin submissions through the Endless Sky Community discord; various people sent me ones that they had and submitted ones that they could find; Titans looks to have been submitted to me by someone named DJF113
https://discord.com/channels/251118043411775489/431496424992014347/954147268238393375

**Comment by VaelophisNyx** [comment]
Aha, neat to know folks liked what little was there enough to keep it around
