### ISSUE TITLE
Change to RW Ships info

### ISSUE THREAD

**Issue by 43897689431805741092** [Hecter94/EndlessSky-PluginArchive#192]
New website link: https://www.moddb.com/mods/rw-ships
No direct file link (i.e. the Github-pointing one is to be removed) as new versions are posted as new files instead of replacing existing ones.
Github repository will be deleted.

**Comment by TheGiraffe3** [comment]
Do note that it's easier to access on GitHub for most people. Would you have to delete the repository?

**Comment by 43897689431805741092** [comment]
> Do note that it's easier to access on GitHub for most people. Would you have to delete the repository?
The Github version hasn't been updated as I am intent on deleting my account after folks have had some time to review any issues I've posted (since they will get deleted). One effect of account deletion this is that all my repositories will be deleted as well.

**Comment by 43897689431805741092** [comment]
> Do note that it's easier to access on GitHub for most people. Would you have to delete the repository?

I am intent on deleting my Github account

**Comment by 43897689431805741092** [comment]
> Do note that it's easier to access on GitHub for most people. Would you have to delete the repository?

The plugin hasn't been maintained here as I am intent on deleting my Github account after folks have had time to review any issues I've posted (since these will get deleted). This means any of my repositories will also get deleted.

**Comment by Hecter94** [comment]
@43897689431805741092  Please take a look at #193 and confirm that's correct.

**Comment by 43897689431805741092** [comment]
> @43897689431805741092 Please take a look at #193 and confirm that's correct.

Yep, looks good, thanks!
