### ISSUE TITLE
Idea: Use submodules for plugins

### ISSUE THREAD

**Issue by TheGiraffe3** [Hecter94/EndlessSky-PluginArchive#197]
@zuckung mentioned that the repository is getting above the space limit for free repositories.

For the plugins in the archive that have GitHub repositories, would it be possible to create submodules so that you won't have to pay for hosting this?

**Comment by zuckung** [comment]
tbh it's over the limit for at least a year. not sure if github messaged hecter lately or if they ignore it. or if hecter is paying now.

submodules like what?

**Comment by Hecter94** [comment]
GitHub is usually pretty lax about it. They haven't contacted me, and from what I've read about it, they will almost always give it a pass if it's not massively over the space limit and it's getting a decent amount of activity, which this is. 
Again, from what I've read, they also tend to be pretty forgiving when it comes to open-source projects, so I don't think we need to worry about it. 

If they do contact me and say that we have to change something, we still have a few options we can do before needing to split the repository up, like [git maintenance](https://git-scm.com/docs/git-maintenance) or [git reflog](https://git-scm.com/docs/git-reflog).

Feel free to try those tools and see how much they can reduce the space and PR the results.
Personally, I wouldn't worry about it until GitHub says it's an issue, though, given we have a decent amount of activity and are for an open-source project.
