### ISSUE TITLE
Asset Repository.

### ISSUE THREAD

**Issue by Hecter94** [Hecter94/EndlessSky-PluginArchive#9]
I'd like to put together a repository of all assets included in various plugins. Ships/Outfits/Landscapes etc. Sorted by copyright. 
Something other modders could make use of, or for inclusion into the base game if we ever want to re-use old, well modelled assets. 

I'd like to see this first split into what copyright category they fall into, and then sorted into what their in-game usage is. 

Need some way to extract these images, determine what copyright they fall under, and then what in-game category they fall in so they can be categorized properly. 

Should this be a separate repo? Or part of the plugin archive?

**Comment by 1010todd** [comment]
While there's probably not much source for plugins around it can still get big really quick, it should be a separate repo. Also so people who clone it to their computer don't get clogged up with the source files.

For copyright categorization maybe we can start from vanilla-compatible as ones that shared under the same license or compatible license with vanilla assets(GPLv3, MIT, etc.) restricted, and unknown. As for determining, it's probably best to find written text by the author on what license they distribute it under, whether it'll be a text file somewhere or some message on Discord. It'll probably be very difficult to find as I believe people rarely mention that.

**Comment by Hecter94** [comment]
I agree that it is best to separate them, thus I've created a new Repo for this per your suggestion:
https://github.com/Hecter94/EndlessSky-PluginAssets

I will leave this issue open for now, but I will be creating new issues on the new repo to deal with tracking copyright and categorizing assets. 

I agree that trying to track down copyright on 300+ mods is going to be near impossible, but I think it's worth doing. There is a lot of great work done here that no-one can make use of currently and I'd like to make it more accessible for those who are looking to make content but don't have the ability to model.
